# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CZToken' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CZToken
pod 'MJExtension'
pod 'SDWebImage', '~> 4.0'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'AFNetworking', '~> 3.0'
pod 'MBProgressHUD', '~> 1.0.0’
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'RCRunkeeperSwitch'
pod 'FDFullscreenPopGesture', '1.1'
end
